### ISSUE TITLE
Compatibility Inquiry: Support for Apollo 6 in pycyber Component

### ISSUE THREAD

**Issue by btcreater** [daohu527/pycyber#11]
I use `cyber_channel echo [channel name]` or other command, the pycyber not work in `apollo 6.0`
Could you please confirm whether pycyber supports Apollo 6 or if there are any plans to provide compatibility in the near future? We greatly value the functionalities provided by pycyber and would like to ensure a seamless integration with the latest version of Apollo.

**Comment by daohu527** [comment]
Apollo 6.0 itself supports cyber command, I don't understand why you use it like this?

**Comment by btcreater** [comment]
> Apollo 6.0 itself supports cyber command, I don't understand why you use it like this?

Perhaps I didn't clarify my experimental environment well. I hope to monitor and collect certain data on the host machine where not in Apollo Docker, through a specific channel.

**Comment by daohu527** [comment]
If you work in docker host mode, then you can't communicate between the host and the container, which is determined by the docker policy.

If you want to communicate in a physical machine, you must use the docker bridge mode

**Comment by btcreater** [comment]
> If you work in docker host mode, then you can't communicate between the host and the container, which is determined by the docker policy.
> 
> If you want to communicate in a physical machine, you must use the docker bridge mode

thanks, after setting bridge mode of docker , pycyber works!
