### ISSUE TITLE
Initializing cyber node without using environment variable

### ISSUE THREAD

**Issue by YuqiHuai** [daohu527/pycyber#8]
Hi, thank you for the amazing tools!

I want to ask you if it is possible to use CYBER_IP as a parameter when initializing (e.g. `cyber.init(cyber_ip='111.222.333.444')`), rather than using an environment variable.

```bash
export CYBER_IP=127.0.0.1
```

**Comment by daohu527** [comment]
As pycyber is a wrap of apollo cyber, cyber does not currently support this assignment method. Therefore I do not intend to support the above interfaces unless necessary!

**Comment by YuqiHuai** [comment]
Cool! Thanks for answering!
